export const  GET_USER_MESSAGES_FAIL  = 'GET_USER_MESSAGES_FAIL'
export const GET_USER_MESSAGES_REQUEST = 'GET_USER_MESSAGES_REQUEST'
export const GET_USER_MESSAGES_SUCCESS ='GET_USER_MESSAGES_SUCCESS'
export const GET_CREARE_USER_MESSAGES_CREAR_ERROR='GET_CREARE_USER_MESSAGES_CREAR_ERROR'


export const GET_Message_USER_REQUEST = 'GET_Message_USER_REQUEST'
export const GET_Message_USER_SUCCESS = 'GET_Message_USER_SUCCESS'
export const GET_Message_USER_FAIL = 'GET_Message_USER_FAIL'


export const CREATE_MESSAGE_REQUEST = 'CREATE_MESSAGE_REQUEST'
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS'
export const CREATE_MESSAGE_FAIL = 'CREATE_MESSAGE_FAIL'