export const POST_CREATE_REQUIEST = 'POST_CREATE_REQUIEST'
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS'
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL'


export const POST_GET_REQUEST = 'POST_GET_REQUEST'
export const POST_GET_SUCCESS = 'POST_GET_SUCCESS'
export const POST_GET_FAIL = 'POST_GET_FAIL'



export const GET_USER_POST_REQUEST = 'GET_USER_POST_REQUEST'
export const GET_USER_POST_SUCCESS = 'GET_USER_POST_SUCCESS'
export const GET_USER_POST_FAIL = 'GET_USER_POST_FAIL'


export const CREATE_COVER_SUCCESS = 'CREATE_COVER_SUCCESS'
export const CREATE_COVER_REQUEST = 'CREATE_COVER_REQUEST'
export const CREATE_COVER_FAIL = 'CREATE_COVER_FAIL'


export const MY_POST_REQUEST = 'MY_POST_REQUEST'
export const MY_POST_SUCCESS = 'MY_POST_SUCCESS'
export const MY_POST_FAIL = 'MY_POST_FAIL'


export const POST_LIKE_SUCCESS = 'POST_LIKE_SUCCESS'
export const POST_LIKE_FAIL = 'POST_LIKE_FAL'
export const POST_LIKE_REQUEST = 'POST_LIKE_REQUEST'


export const MY_POST_DELETE_SUCCESS = 'MY_POST_DELETE_SUCCESS'
export const MY_POST_DELETE_REQUEST = 'MY_POST_DELETE_REQUEST'
export const MY_POST_DELETE_FAIL = 'MY_POST_DELETE_FAIL'
export const MY_POST_RESET = 'MY_POST_RESET'