export const REGISTER_CREATE_REQUIEST = 'REGISTER_CREATE_REQUIEST'
export const REGISTER_CREATE_SUCCESS = 'REGISTER_CREATE_SUCCESS'
export const REGISTER_CREATE_FAIL = 'REGISTER_CREATE_FAIL'


export const LOGIN_CREATE_REQUIEST = 'LOGIN_CREATE_REQUIEST'
export const LOGIN_CREATE_SUCCESS = 'LOGIN_CREATE_SUCCESS'
export const LOGIN_CREATE_FAIL = 'LOGIN_CREATE_FAIL' 
export const REGISTER_ERROR_CLEAR = 'REGISTER_ERROR_CLEAR'
export const LOGIN_ERROR_CLEAR = 'LOGIN_ERROR_CLEAR'


export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'


export const PROFILE_UPDATE_REQUIEST='PROFILE_UPDATE_REQUIEST'
export const PROFILE_UPDATE_SUCCESS='PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_FAIL='PROFILE_UPDATE_FAIL'

export const PROFILE_UPDATE_RESET = 'PROFILE_UPDATE_RESET'


 export const PROFILE_SINGLE_GET_REQUIEST ='PROFILE_SINGLE_GET_REQUIEST'
 export const PROFILE_SINGLE_GET_SUCCESS = 'PROFILE_SINGLE_GET_SUCCESS'
 export const PROFILE_SINGLE_GET_FAIL = 'PROFILE_SINGLE_GET_FAIL'


export const GET_ALL_USERS_REQUIEST ='GET_ALL_USERS_REQUIEST'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL'


export const GET_SINGLE_USERS_REQUIEST = 'GET_SINGLE_USERS_REQUIEST'
export const GET_SINGLE_USERS_SUCCESS = 'GET_SINGLE_USERS_SUCCESS'
export const GET_SINGLEL_USERS_FAIL = 'GET_SINGLEL_USERS_FAIL'


export const FOLLOW_USERS_REQUIEST = 'FOLLOW_USERS_REQUIEST'
export const FOLLOW_USERS_SUCCESS = 'FOLLOW_USERS_SUCCESS'
export const FOLLOW_USERS_FAIL = 'FOLLOW_USERS_FAIL'
  

